### ISSUE TITLE
Method for saving all images in the scene

### ISSUE THREAD

**Issue by WangJuan6** [allenai/procthor#40]
Dear author,
your work is excellent. I want to know if is there any method to save all images in the house at once. I try to access the image by teleporting the agent to the all reachable position, but this method is too slow.
Thanks
Juan

**Comment by sarthakchittawar** [comment]
You could create multiple third party cameras and then get the image data from each one using the third party camera metadata.

**Comment by WangJuan6** [comment]
Thanks for your reply, I will try this method.
