### ISSUE TITLE
Documentation/Description

### ISSUE THREAD

**Issue by sarthakchittawar** [allenai/procthor#41]
Hi team,
It was mentioned in the ProcTHOR paper that the dataset .json files would be released as open source, when can we expect it?
If not, is there a documentation of the toolset to create a dataset using ProcTHOR? I'd really like to know if there is one, as it's a bit confusing to deal with the raw code right now.

**Comment by mattdeitke** [comment]
The dataset is released :)

Please see the website for a demo on how to use it: https://colab.research.google.com/drive/1Il6TqmRXOkzYMIEaOU9e4-uTDTIb5Q78

The JSON files of the houses are available here: https://github.com/allenai/procthor-10k
