### ISSUE TITLE
How to eval the procthor-model in https://github.com/allenai/procthor-models? 

### ISSUE THREAD

**Issue by hutchinsonian** [allenai/procthor#42]
I run the 
```
python allenact/main.py projects/objectnav_baselines/experiments/robothor/clip/objectnav_robothor_rgb_clipresnet50gru_ddppo.py -o storage/objectnav_10k_rgb_resnet50gru_ddppo -c pretrained_model_ckpts/procthor-models/scale_ablation/exp_10k-houses__stage_02__steps_000195225491.pt --eval
```
And i got this error
```
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResnetTensorNavActorCritic:
        Unexpected key(s) in state_dict: "prev_action_embedder.fc.weight". 
        size mismatch for goal_visual_encoder.embed_goal.weight: copying a param with shape torch.Size([16, 32]) from checkpoint, the shape in current model is torch.Size([12, 32]).
        size mismatch for state_encoders.single_belief.rnn.weight_ih_l0: copying a param with shape torch.Size([1536, 1574]) from checkpoint, the shape in current model is torch.Size([1536, 1568]).
```
It looks like the configuration file you are using for training on procthor-10k is different from  `objectnav_robothor_rgb_clipresnet50gru_ddppo.py`. How should I modify the file?

**Comment by WangJuan6** [comment]
Hi,
I also encountered the same problem, did you solve it?
Thanks

**Comment by hutchinsonian** [comment]
> Hi, I also encountered the same problem, did you solve it? Thanks

It is mentioned in the paper that the author has made some modifications to the EmbCLIP model, to add the types of navigation objects, that is, the input channels have increased. You need to modify some parameters as mentioned in the paper. But the author did not release the relevant code.

**Comment by WangJuan6** [comment]
OK, thanks for your reply!
